In [1]:
from __future__ import print_function
import os
data_path = ['C:\\data']
import pandas as pd
# Import the data using the file path
filepath = os.sep.join(data_path + ['Orange_Telecom_Churn_Data.csv'])
data = pd.read_csv(filepath)
data.head().T

0         1         2         3  \
state                                KS        OH        NJ        OH   
account_length                      128       107       137        84   
area_code                           415       415       415       408   
phone_number                   382-4657  371-7191  358-1921  375-9999   
intl_plan                            no        no        no       yes   
voice_mail_plan                     yes       yes        no        no   
number_vmail_messages                25        26         0         0   
total_day_minutes                 265.1     161.6     243.4     299.4   
total_day_calls                     110       123       114        71   
total_day_charge                  45.07     27.47     41.38      50.9   
total_eve_minutes                 197.4     195.5     121.2      61.9   
total_eve_calls                      99       103       110        88   
total_eve_charge                  16.78     16.62      10.3      5.26   
total_night_minutes               244.7     254.4     162.6     196.9   
total_night_calls                    91       103       104        89   
total_night_charge                11.01     11.45      7.32      8.86   
total_intl_minutes                   10      13.7      12.2       6.6   
total_intl_calls                      3         3         5         7   
total_intl_charge                   2.7       3.7      3.29      1.78   
number_customer_service_calls         1         1         0         2   
churned                           False     False     False     False   

                                      4  
state                                OK  
account_length                       75  
area_code                           415  
phone_number                   330-6626  
intl_plan                           yes  
voice_mail_plan                      no  
number_vmail_messages                 0  
total_day_minutes                 166.7  
total_day_calls                     113  
total_day_charge                  28.34  
total_eve_minutes                 148.3  
total_eve_calls                     122  
total_eve_charge                  12.61  
total_night_minutes               186.9  
total_night_calls                   121  
total_night_charge                 8.41  
total_intl_minutes                 10.1  
total_intl_calls                      3  
total_intl_charge                  2.73  
number_customer_service_calls         3  
churned                           False

In [2]:
# Remove extraneous columns
data.drop(['state', 'area_code', 'phone_number'], axis=1, inplace=True)
data.columns
from sklearn.preprocessing import LabelBinarizer
#tf를 01로 고치기
lb = LabelBinarizer()
for col in ['intl_plan', 'voice_mail_plan', 'churned']:
    data[col] = lb.fit_transform(data[col])
data.head()

account_length  intl_plan  voice_mail_plan  number_vmail_messages  \
0             128          0                1                     25   
1             107          0                1                     26   
2             137          0                0                      0   
3              84          1                0                      0   
4              75          1                0                      0   

   total_day_minutes  total_day_calls  total_day_charge  total_eve_minutes  \
0              265.1              110             45.07              197.4   
1              161.6              123             27.47              195.5   
2              243.4              114             41.38              121.2   
3              299.4               71             50.90               61.9   
4              166.7              113             28.34              148.3   

   total_eve_calls  total_eve_charge  total_night_minutes  total_night_calls  \
0               99             16.78                244.7                 91   
1              103             16.62                254.4                103   
2              110             10.30                162.6                104   
3               88              5.26                196.9                 89   
4              122             12.61                186.9                121   

   total_night_charge  total_intl_minutes  total_intl_calls  \
0               11.01                10.0                 3   
1               11.45                13.7                 3   
2                7.32                12.2                 5   
3                8.86                 6.6                 7   
4                8.41                10.1                 3   

   total_intl_charge  number_customer_service_calls  churned  
0               2.70                              1        0  
1               3.70                              1        0  
2               3.29                              0        0  
3               1.78                              2        0  
4               2.73                              3        0

In [3]:
data_1 = data
data_2 = data
data_3 = data

In [5]:
# Mute the sklearn warning
import warnings
warnings.filterwarnings('ignore', module='sklearn')
#sklearn은 기본적으로 넘파이형으로 받음
#최대 최소 1,0으로 바꾸기
from sklearn.preprocessing import MinMaxScaler

msc = MinMaxScaler()

data_msc = pd.DataFrame(msc.fit_transform(data_1),  # this is an np.array, not a dataframe.
                    columns=data_1.columns)
data_msc.head()

account_length  intl_plan  voice_mail_plan  number_vmail_messages  \
0        0.524793        0.0              1.0               0.480769   
1        0.438017        0.0              1.0               0.500000   
2        0.561983        0.0              0.0               0.000000   
3        0.342975        1.0              0.0               0.000000   
4        0.305785        1.0              0.0               0.000000   

   total_day_minutes  total_day_calls  total_day_charge  total_eve_minutes  \
0           0.754196         0.666667          0.754183           0.542755   
1           0.459744         0.745455          0.459672           0.537531   
2           0.692461         0.690909          0.692436           0.333242   
3           0.851778         0.430303          0.851740           0.170195   
4           0.474253         0.684848          0.474230           0.407754   

   total_eve_calls  total_eve_charge  total_night_minutes  total_night_calls  \
0         0.582353          0.542866             0.619494           0.520000   
1         0.605882          0.537690             0.644051           0.588571   
2         0.647059          0.333225             0.411646           0.594286   
3         0.517647          0.170171             0.498481           0.508571   
4         0.717647          0.407959             0.473165           0.691429   

   total_night_charge  total_intl_minutes  total_intl_calls  \
0            0.619584               0.500              0.15   
1            0.644344               0.685              0.15   
2            0.411930               0.610              0.25   
3            0.498593               0.330              0.35   
4            0.473270               0.505              0.15   

   total_intl_charge  number_customer_service_calls  churned  
0           0.500000                       0.111111      0.0  
1           0.685185                       0.111111      0.0  
2           0.609259                       0.000000      0.0  
3           0.329630                       0.222222      0.0  
4           0.505556                       0.333333      0.0

In [7]:
#StandardScaler
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
#sklearn은 기본적으로 넘파이형으로 받음

data_ss = pd.DataFrame(ss.fit_transform(data_2),  # this is an np.array, not a dataframe.
                    columns=data_2.columns)
data_ss.head()

account_length  intl_plan  voice_mail_plan  number_vmail_messages  \
0        0.698941  -0.323240         1.667120               1.273145   
1        0.169849  -0.323240         1.667120               1.346973   
2        0.925695  -0.323240        -0.599837              -0.572549   
3       -0.409634   3.093675        -0.599837              -0.572549   
4       -0.636388   3.093675        -0.599837              -0.572549   

   total_day_minutes  total_day_calls  total_day_charge  total_eve_minutes  \
0           1.573802         0.502824          1.574074          -0.064032   
1          -0.346802         1.158422         -0.347082          -0.101621   
2           1.171125         0.704546          1.171286          -1.571562   
3           2.210292        -1.463971          2.210457          -2.744745   
4          -0.252163         0.654116         -0.252115          -1.035419   

   total_eve_calls  total_eve_charge  total_night_minutes  total_night_calls  \
0        -0.060077         -0.063849             0.876999          -0.446928   
1         0.141693         -0.101089             1.068992           0.154374   
2         0.494791         -1.572084            -0.748012           0.204483   
3        -0.614946         -2.745155            -0.069110          -0.547145   
4         1.100103         -1.034426            -0.267041           1.056327   

   total_night_charge  total_intl_minutes  total_intl_calls  \
0            0.876286           -0.094809         -0.584236   
1            1.069818            1.245227         -0.584236   
2           -0.746737            0.701969          0.229917   
3           -0.069377           -1.326194          1.044069   
4           -0.267307           -0.058592         -0.584236   

   total_intl_charge  number_customer_service_calls   churned  
0          -0.095509                      -0.436676 -0.405816  
1           1.245982                      -0.436676 -0.405816  
2           0.695971                      -1.202236 -0.405816  
3          -1.329681                       0.328885 -0.405816  
4          -0.055264                       1.094445 -0.405816

In [8]:
# Mute the sklearn warning
from sklearn.preprocessing import MaxAbsScaler
mas = MaxAbsScaler()

data_mas = pd.DataFrame(mas.fit_transform(data_3),  # this is an np.array, not a dataframe.
                    columns=data_3.columns)
data_mas.head()

account_length  intl_plan  voice_mail_plan  number_vmail_messages  \
0        0.526749        0.0              1.0               0.480769   
1        0.440329        0.0              1.0               0.500000   
2        0.563786        0.0              0.0               0.000000   
3        0.345679        1.0              0.0               0.000000   
4        0.308642        1.0              0.0               0.000000   

   total_day_minutes  total_day_calls  total_day_charge  total_eve_minutes  \
0           0.754196         0.666667          0.754183           0.542755   
1           0.459744         0.745455          0.459672           0.537531   
2           0.692461         0.690909          0.692436           0.333242   
3           0.851778         0.430303          0.851740           0.170195   
4           0.474253         0.684848          0.474230           0.407754   

   total_eve_calls  total_eve_charge  total_night_minutes  total_night_calls  \
0         0.582353          0.542866             0.619494           0.520000   
1         0.605882          0.537690             0.644051           0.588571   
2         0.647059          0.333225             0.411646           0.594286   
3         0.517647          0.170171             0.498481           0.508571   
4         0.717647          0.407959             0.473165           0.691429   

   total_night_charge  total_intl_minutes  total_intl_calls  \
0            0.619584               0.500              0.15   
1            0.644344               0.685              0.15   
2            0.411930               0.610              0.25   
3            0.498593               0.330              0.35   
4            0.473270               0.505              0.15   

   total_intl_charge  number_customer_service_calls  churned  
0           0.500000                       0.111111      0.0  
1           0.685185                       0.111111      0.0  
2           0.609259                       0.000000      0.0  
3           0.329630                       0.222222      0.0  
4           0.505556                       0.333333      0.0

In [11]:
#데이터 분리하기
#Get a list of all the columns that don't contain the label
x_cols1 = [x for x in data_msc.columns if x != 'churned']
x_cols2 = [x for x in data_ss.columns if x != 'churned']
x_cols3 = [x for x in data_mas.columns if x != 'churned']

# Split the data into two dataframes
#x데이터에 churned를 빼고 다시 넣어줌
X_data1 = data_msc[x_cols1]
y_data1 = data_msc['churned']
X_data2 = data_ss[x_cols2]
y_data2 = data_ss['churned']
X_data3 = data_mas[x_cols3]
y_data3 = data_mas['churned']

# # alternatively:
# X_data = data.copy()
# y_data = X_data.pop('churned')

In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors=3)
knn1 = knn1.fit(X_data1, y_data1)
y_pred1 = knn1.predict(X_data1)
y_pred1

array([0., 0., 0., ..., 0., 0., 0.])

In [29]:
#정확도 구하기식
# Function to calculate the % of values that were correctly predicted
# 비교해서 정확도 재는 알고리즘 만들고 출력하기
def accuracy(real, predict):
    #같을때는 더해줌 
    return sum(real == predict) / float(real.shape[0])

In [30]:
print(accuracy(y_data1, y_pred1))

0.9422


In [31]:
knn2 = KNeighborsClassifier(n_neighbors=3)
knn2 = knn2.fit(X_data2, y_data1)#y_data2는(원래 T,F이지만) 0과 1로만 나타내어 지지 않음!!!
y_pred2 = knn2.predict(X_data2)
y_pred2

array([0., 0., 0., ..., 0., 0., 0.])

In [32]:
print(accuracy(y_data1, y_pred2))

0.9396


In [33]:
knn3 = KNeighborsClassifier(n_neighbors=3)
knn3 = knn3.fit(X_data3, y_data3)
y_pred3 = knn3.predict(X_data3)
y_pred3

array([0., 0., 0., ..., 0., 0., 0.])

In [34]:
print(accuracy(y_data3, y_pred3))

0.942
